Repository ni/monodrive-documentation, pull requests merged in 2020-07, with the labels that each got.

#159 Documentation: Collision Sensor
  docs/monoDrive_home/Collision.md
  mkdocs.yml
Labels: documentation

#162 Semantic lidar
  docs/monoDrive_home/Lidar.md
  docs/monoDrive_home/img/lidar.png
  docs/monoDrive_home/img/semantic_lidar.png
Labels: documentation, enhancement

#164 Update state sensor
  docs/monoDrive_home/State-sensor.md
Labels: documentation, update

#165 Update simulator configuration
  docs/monoDrive_home/Simulator-Configuration.md
Labels: documentation, update

#166 CarSim Instructions
  docs/monoDrive_home/CarSim.md
  docs/monoDrive_home/Vehicle-Configuration.md
  mkdocs.yml
Labels: documentation, enhancement

#171 Vehicle PhysX
  docs/monoDrive_home/Vehicle-PhysX.md
  docs/monoDrive_home/img/engine_config.png
  docs/monoDrive_home/img/mass_config.png
  docs/monoDrive_home/img/steering_config.png
  docs/monoDrive_home/img/wheel_config1.png
  docs/monoDrive_home/img/wheel_config2.png
  docs/monoDrive_home/img/wheel_config3.png
  mkdocs.yml
Labels: documentation, enhancement

#174 Real-to-Virtual Data Products Documentation
  docs/r2v/data_processing_output.md
  docs/r2v/imgs/classified_cloud.png
  docs/r2v/imgs/final_textured_road_mesh.png
  docs/r2v/imgs/final_textured_road_mesh_closeup.png
  docs/r2v/imgs/foliage_cloud.png
  docs/r2v/imgs/full_gnss_path.png
  docs/r2v/imgs/road_cloud.png
  mkdocs.yml
Labels: documentation, enhancement

#176 Add class label description to R2V data products
  docs/r2v/data_processing_output.md
  docs/r2v/r2v_maps.md
Labels: documentation, enhancement

#177 Add Class Labels for R2V Data
  docs/r2v/data_processing_output.md
  docs/r2v/r2v_maps.md
Labels: documentation, enhancement

#183 Added IMU coordinate frame references
  docs/monoDrive_home/IMU.md
Labels: documentation, enhancement

#184 Development
  docs/monoDrive_home/IMU.md
Labels: documentation
