Repository ni/monodrive-documentation, pull requests merged in 2020-11, with the labels that each got.

#222 Add LV client documentation for fisheye camera
  docs/LV_client/sensors/mono_fisheye_camera.png
  docs/LV_client/sensors/mono_fisheye_camera_poly1.md
  docs/LV_client/sensors/mono_fisheye_camera_poly1.png
  docs/LV_client/sensors/mono_fisheye_equidistant_camera.md
  docs/LV_client/sensors/mono_fisheye_equidistant_camera.png
  mkdocs.yml
Labels: documentation

#216 Adding New Vehicle Model Link
  docs/css/extra.css
  docs/index.md
  docs/monoDrive_home/Vehicle-Configuration.md
  docs/unreal_tutorials/FoliagePainting.md
  docs/unreal_tutorials/MayaWheels.md
  docs/unreal_tutorials/PlacingSigns.md
  docs/unreal_tutorials/SingularMesh.md
  docs/unreal_tutorials/SplineMesh.md
  mkdocs.yml
Labels: enhancement

#227 Add documentation for LV VIs
  docs/LV_client/sensors/mono_led_array.md
  docs/LV_client/sensors/mono_led_array.png
  docs/LV_client/shared_libraries/mono_lane_follower_lights.md
  docs/LV_client/shared_libraries/mono_lane_follower_lights.png
  docs/LV_client/shared_libraries/mono_light_API_example.md
  docs/LV_client/shared_libraries/mono_light_API_example.png
  docs/LV_client/shared_libraries/mono_light_API_replay_example.md
  docs/LV_client/shared_libraries/mono_light_API_replay_example.png
  docs/LV_client/tools/mono_generate_LED_configuration.md
  docs/LV_client/tools/mono_generate_LED_configuration.png
  mkdocs.yml
Labels: documentation

#231 Add image for camera coordinate frame and fix typo on the center tag …
  docs/monoDrive_home/Camera.md
  docs/monoDrive_home/img/camera_reference.png
Labels: bug, enhancement

#228 Adding documentation fot the lights API
  docs/monoDrive_home/Lighting API.md
  docs/monoDrive_home/img/lights.png
  mkdocs.yml
Labels: documentation
