Repository ni/monodrive-documentation, pull requests merged in 2020-05, with the labels that each got.

#112 Sensor Configuration Updates
  docs/Radar.md
  docs/monoDrive_home/Camera.md
  docs/monoDrive_home/Common.md
  docs/monoDrive_home/GPS.md
  docs/monoDrive_home/IMU.md
  docs/monoDrive_home/Lidar.md
  docs/monoDrive_home/RPM.md
  docs/monoDrive_home/Radar.md
  docs/monoDrive_home/State-sensor.md
  docs/monoDrive_home/Ultrasonic.md
  docs/monoDrive_home/Viewport.md
Labels: bug, documentation

#115 C++ and Python Weather
  docs/monoDrive_home/Weather.md
Labels: documentation, enhancement

#116 Intro to simulator API
  docs/monoDrive_home/API.md
  mkdocs.yml
Labels: documentation, enhancement

#120 Development
  docs/monoDrive_home/API.md
  docs/monoDrive_home/Weather.md
  mkdocs.yml
Labels: documentation

#118 Wheel integration
  docs/LV_client/tutorials/AddSensors.md
  docs/LV_client/tutorials/Lidar.md
  docs/LV_client/tutorials/Loading_Maps.md
  docs/LV_client/tutorials/Remote_Connection.md
  docs/LV_client/tutorials/Sensor_Palette.md
  docs/LV_client/tutorials/Setup.md
  docs/LV_client/tutorials/Simulator_configuration.md
  docs/LV_client/tutorials/Weather.md
  docs/LV_client/tutorials/wheel_integration.md
  mkdocs.yml
Labels: documentation
